### ISSUE TITLE
Dockerizing Bittext Env. 

### ISSUE THREAD

**Issue by russeree** [russeree/bittext#1]
To enable ease of deployment as well as a standardized runtime environment a docker base image and  docker file needs to be created for the bittext project.

This docker container should support the following software on startup, either building at startup or preinstalled

- [ ] bitcoin core .22
- [ ] core lightning .11 or greater
- [ ] node 18.2 w/ npm

In regards to Dockerizing  bitcoin core please let the docker image point to a mounted bitcoin core data directory as to reduce the need to re-download or store the blockchain image in the docker container.

This task is high priority. 

Thanks/

**Comment by Herrytheeagle** [comment]
![Untitled 3](https://user-images.githubusercontent.com/30316855/170166471-b3b49674-31ea-4325-9504-9fd8d903da63.png)
Got the remote repo cloned on my local device perfectly

![Untitled](https://user-images.githubusercontent.com/30316855/170166798-7cabe704-349e-46ee-b1f9-28346cb853ea.png)
Couldn't create the "Dockerfile" because it keeps generating this error

I tried running this command on the CLI to fix that $ sudo chown -R herrytheeagle /com.docker.devenvironments.code.git

**Comment by russeree** [comment]
I have patched the Dockerfile please clone and run again. It should work now.

As a note this is designed to be built and run with Docker CLI.

**Comment by nully0x** [comment]
I believe this issue has been fixed right?

**Comment by Herrytheeagle** [comment]
> I believe this issue has been fixed right?

Yes, Clone and Run it locally

**Comment by nully0x** [comment]
> > I believe this issue has been fixed right?
> 
> Yes, Clone and Run it locally

I believe it should be closed while accommodating other issues that might be raised.

**Comment by nully0x** [comment]
> > I believe this issue has been fixed right?
> 
> Yes, Clone and Run it locally

I think it's should be labeled closed.
